Return-Path: <letrungcaotung@gmail.com>
X-Original-To: ysxzxjfidl@mail.tdkiller.tk
Delivered-To: ysxzxjfidl@mail.tdkiller.tk
Received: from mail-qk1-f182.google.com (mail-qk1-f182.google.com [209.85.222.182])
	by mail.tdkiller.tk (Postfix) with ESMTPS id 928F43FDB4
	for <ysxzxjfidl@mail.tdkiller.tk>; Sun,  8 Mar 2020 22:10:24 -0600 (MDT)
Received: by mail-qk1-f182.google.com with SMTP id f3so8051266qkh.1
        for <ysxzxjfidl@mail.tdkiller.tk>; Sun, 08 Mar 2020 21:10:24 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20161025;
        h=mime-version:from:date:message-id:subject:to;
        bh=Z3P7lwMQrir9fgttJoZeC6OMZZRVE+MlpL/6hiykZ5k=;
        b=Pa/JStdhpGN4PQgFDRWI/JBhKG+bFMPVLp2iSiey3KRfSFVx6tmek6c+gGbouji9B8
         Y7dAE4novIBQvzNU0Jqa3e73H/PsQOHqncNOXYBrvn6qEd2dOPKAvvaewqz9wil6GXho
         JJJr7WeeXqf6A83S3Z8i9tSiBMw9RUvVV6iKjJ5eJ1jex+ZUcUoRM7nymawNdfqIufHx
         swK+R8xEEtiPHhdvjvv5z2ddiHHWwoiS/XwrHtRGOGvGf7GT3UNp7NYrl7jawIuzyKBO
         YGuXDr1Rx5T/qW0xbP8eJtqJnTHYnH0vK8Qli/WI810HOjvrrkxBoBjE1na6hLJHW3/8
         5tAw==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:mime-version:from:date:message-id:subject:to;
        bh=Z3P7lwMQrir9fgttJoZeC6OMZZRVE+MlpL/6hiykZ5k=;
        b=tj8Dy2NonCnbKNC5IIM5mY/dMXAtbKQJ/TNIGVuJ658Ptc1U72ltJ9zQWy0q+FjvQ7
         h1zPnK70WJfd1Q5lAesRC/vZAouDK+mXu8y0dPe6bstFDI1NmAFWS4PkLUUvwCFPua9L
         NhDdemhQ7dyeCqZATGpueUjOwbyuGfj1/w4krg8zaQRwPUouVGyNjtt4ZQJP5aAVWcsQ
         R3ZGxcTjjayE/WhTYQbNW+ndvcv8K/IReTlG/ejilaVu01yvw74HNfhsZLFUIMJLnnA2
         Nd39By070rRrapnNgvS7nX2K9r7DJfERnqlU7AUmIya54ATSIkrIcnYt0rERmz4DviBF
         YXKQ==
X-Gm-Message-State: ANhLgQ1so+vYufVbd1OYNdeiw9fnwANt7KljpYEoPLrUgIWEn66p+IX1
	l0ysmuZ2/UiZCIKDtjOHyZVFTBYl68BZiO6sF2yso2lh
X-Google-Smtp-Source: ADFU+vsD9sUooVuMVRnG/p1tqtwFQwfq+bBnnGWP7jcdQceng4+HkzYU2iLEDJPySxKmH7n2FPGakFvpQq6FDO9DYc8=
X-Received: by 2002:a05:620a:691:: with SMTP id f17mr13032825qkh.342.1583727023548;
 Sun, 08 Mar 2020 21:10:23 -0700 (PDT)
MIME-Version: 1.0
From: Tin Lee <letrungcaotung@gmail.com>
Date: Sun, 8 Mar 2020 22:10:11 -0600
Message-ID: <CAMCP6838Rd4dUoC5ttFEGUsgVH5xQAFrpghZGNy-QCGBtb3WHw@mail.gmail.com>
Subject: something
To: ysxzxjfidl@mail.tdkiller.tk
Content-Type: multipart/alternative; boundary="000000000000a8eb3b05a0642e18"

--000000000000a8eb3b05a0642e18
Content-Type: text/plain; charset="UTF-8"

something

--000000000000a8eb3b05a0642e18
Content-Type: text/html; charset="UTF-8"

<div dir="ltr">something</div>

--000000000000a8eb3b05a0642e18--
