Return-Path: <letrungcaotung@gmail.com>
X-Original-To: odwailwkdd@mail.tdkiller.tk
Delivered-To: odwailwkdd@mail.tdkiller.tk
Received: from mail-qk1-f181.google.com (mail-qk1-f181.google.com [209.85.222.181])
	by mail.tdkiller.tk (Postfix) with ESMTPS id EE39B4054B
	for <odwailwkdd@mail.tdkiller.tk>; Sun,  1 Mar 2020 21:37:59 -0700 (MST)
Received: by mail-qk1-f181.google.com with SMTP id u124so8820549qkh.13
        for <odwailwkdd@mail.tdkiller.tk>; Sun, 01 Mar 2020 20:37:59 -0800 (PST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20161025;
        h=mime-version:from:date:message-id:subject:to;
        bh=2aleDzZii2PifD5+MTY6gELO0kJcOEErAAQv8N9K7Ns=;
        b=j2dO/RVw4SbfJNk65nxKZnLdTwjdewmA7CNwFKVx7zE1pDvWnkubxbMJuL8EdZR5nc
         mIXzd2CC6Gmv9Na770y0ubbcoNlG81Eju7hXuY5cNEMUT0w2AMQiF40tPXcQiXHBojxH
         RBL/Ztoi+2oZ+3hPPKKx4k+C64Hvt5K8iG2ECuYFZ3XaS1gGpR7kOIl8TdfNjNYc64ze
         5Rco2tpNSKnKriPgkJIwn3Oip7Q1y4UizHgTzY9FPbBXNKF4BzjlhzuKHgso3IU6kHd5
         UB5zmgy9onAytToWpm2MUkCqSZDBPKU7Y9jMh2qYsRuSb0n5s5UvAleeQ/guElivISSo
         QpUA==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:mime-version:from:date:message-id:subject:to;
        bh=2aleDzZii2PifD5+MTY6gELO0kJcOEErAAQv8N9K7Ns=;
        b=hHUt8WmlhNtG6KOZchwCOV3CH1kQ2A7q+LiR/X5e27L7tzdKzpbWWWYJhtKx/u3ZRI
         2Kx7ueXKNQEPL0atHIaOVTmYvvGA9rNT1+hJXems83oDU20gowmOymRPBIM7iPbxzWhm
         N7LJGbmok9WdIURR+79c+Jl6ah1glHODKVTNh7IctN/oQZAWmDy/DSV6/fSwkqr88wq+
         Wa3xYguwOXTOoaO2upKS01bHHRK71a/0znxMgepOa8HMFEQ8RYTxiVCa563G7KbmksH8
         zQ5RqDcZWMq+iAOSndZ6KRfAN9v6QxVCXRWNECbEigJovlvANAhIQ0hpb+AqEVoedja3
         mY9Q==
X-Gm-Message-State: APjAAAVEDOd9u+SaBBGQKNBfWSRZCtYyVN/jaHwmN66mmubS3FE+o9Uq
	V9Wp0V2yJBm39zgIaNMIpjXLUczFyXMztDNYKc1kBBzZ
X-Google-Smtp-Source: APXvYqx03MM0ZZz8YaFr+KUQF1hfRLqlGsD+PnshtgRRNYr9J0OE0bKWSn8LG9ZzajDGlw5GgDr2TkyZXaT8vUBal6A=
X-Received: by 2002:ae9:f819:: with SMTP id x25mr15037244qkh.9.1583123878511;
 Sun, 01 Mar 2020 20:37:58 -0800 (PST)
MIME-Version: 1.0
From: Tin Lee <letrungcaotung@gmail.com>
Date: Sun, 1 Mar 2020 21:37:45 -0700
Message-ID: <CAMCP680zJ5y6n+9tXL-XiRDMwhxqoy1owsU+32FGH0t=0FBYMw@mail.gmail.com>
Subject: 11241
To: odwailwkdd@mail.tdkiller.tk
Content-Type: multipart/alternative; boundary="0000000000006a0a22059fd7c00f"

--0000000000006a0a22059fd7c00f
Content-Type: text/plain; charset="UTF-8"

wwgasdgqgw

--0000000000006a0a22059fd7c00f
Content-Type: text/html; charset="UTF-8"

<div dir="ltr">wwgasdgqgw</div>

--0000000000006a0a22059fd7c00f--
