Return-Path: <letrungcaotung@gmail.com>
X-Original-To: qranihedkf@mail.tdkiller.tk
Delivered-To: qranihedkf@mail.tdkiller.tk
Received: from mail-qt1-f182.google.com (mail-qt1-f182.google.com [209.85.160.182])
	by mail.tdkiller.tk (Postfix) with ESMTPS id DD586412DA
	for <qranihedkf@mail.tdkiller.tk>; Fri, 13 Mar 2020 20:20:38 -0600 (MDT)
Received: by mail-qt1-f182.google.com with SMTP id l13so9427460qtv.10
        for <qranihedkf@mail.tdkiller.tk>; Fri, 13 Mar 2020 19:20:38 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20161025;
        h=mime-version:from:date:message-id:subject:to;
        bh=Q/+jhP7KzrfeQtRpu6bv1/sDgYcMkoFDDV+2mqNHr2E=;
        b=L7uaBD7HDVhUIDmRTHUmiANGdeNSqOFqPeBowQSymyt4JN0UDvXa72INZAu7zkPOoK
         YrnfvU5eMJdZkEz1w+rtHr9/wcmFrzRkdRbQrKxaEk0/NF85T1nf3aFT3j43c1ygkoFr
         tk3GbA2ZVUPIc4xoga735jlFbQbQcJ1LISHeZEw7g3PU1/uyR79Qjq3WRUmMTmHDB/X6
         tkU3RbLx+cRQnJjZjKYkmF2B1fL08aMXRYrbC4HdgGQyhFYKWzaNknLuoy42+Wcy+p2P
         pUgTVIJFty1GCQ5hs17LA76hMNPPEYf9rvl+06xu8wt8qZJboh7Bja70rBzAUv5rPvOr
         Bkdw==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:mime-version:from:date:message-id:subject:to;
        bh=Q/+jhP7KzrfeQtRpu6bv1/sDgYcMkoFDDV+2mqNHr2E=;
        b=YEAR14/20ykDlQoAbSeil9PQwbadQWn55kJljiCvhxTfuQH77HOrBfybHDPss/+AEb
         AYxnbHTshedcM0DYyUURWqCkDMZQHsN2qBW/T3pzoFEKZ5Ye3EBxdsX2Nljy2sID3ZaJ
         xkDHpo6Gx35X/Y7ZdEPjSZUYlv6mqaFU/qT28zrhPM+yEFFeiUp2R+pLRtNCHKE7j5W1
         E2+ME/O2oVMIWMPj48GdvgnDFPgwmhF7Vyw6haLq4qAlF5G4eN1KrLgPAukHcEffv7FA
         UaBGem0HGaB/g93Qf5LgTaRplzcg3N3vKMFuC1QTz2KIxyW0vTsZNfKyk98UptI6AVkd
         gSnQ==
X-Gm-Message-State: ANhLgQ1d8grfWsbM0e0MUo5BhNvXuyrWfIDtQRPk3F4nlmIx4dW/yzUv
	GpBvrE4rGTZXTAyuwQgN3zQy1Mdb0liPRv8YCjCv/F5S
X-Google-Smtp-Source: ADFU+vsss9w+trS8qEQq5ev4OofwQnzj4FiBPul3du/TB3vkp3y3mx9weVfMYODXHi4wQ++rxSqFFFGkeaDnp2ZAws8=
X-Received: by 2002:aed:2314:: with SMTP id h20mr8280526qtc.184.1584152436992;
 Fri, 13 Mar 2020 19:20:36 -0700 (PDT)
MIME-Version: 1.0
From: Tin Lee <letrungcaotung@gmail.com>
Date: Fri, 13 Mar 2020 20:20:25 -0600
Message-ID: <CAMCP683ALuofU6GTx6sp0z6aSMzKW6gMxRe1hxqkQ1DJDcqo1Q@mail.gmail.com>
Subject: dgasdga
To: qranihedkf@mail.tdkiller.tk
Content-Type: multipart/alternative; boundary="00000000000046efc605a0c73ba2"

--00000000000046efc605a0c73ba2
Content-Type: text/plain; charset="UTF-8"

asdgq2gdgq3g

--00000000000046efc605a0c73ba2
Content-Type: text/html; charset="UTF-8"

<div dir="ltr">asdgq2gdgq3g</div>

--00000000000046efc605a0c73ba2--
